# Generated by Django 4.2.5 on 2023-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('ano_publicacion', models.CharField(max_length=4)),
                ('mes_publicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('dia_publicacion', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
    ]
